const book={
  Sheets: {
    "Antal per dag region": {
      "!ref": "A1:W389",
      A1: {
        t: "s",
        v: "Statistikdatum",
        r: "<t>Statistikdatum</t>",
        h: "Statistikdatum",
        w: "Statistikdatum",
      },
      B1: {
        t: "s",
        v: "Totalt_antal_fall",
        r: "<t>Totalt_antal_fall</t>",
        h: "Totalt_antal_fall",
        w: "Totalt_antal_fall",
      },
      C1: {
        t: "s",
        v: "Blekinge",
        r: "<t>Blekinge</t>",
        h: "Blekinge",
        w: "Blekinge",
      },
      D1: {
        t: "s",
        v: "Dalarna",
        r: "<t>Dalarna</t>",
        h: "Dalarna",
        w: "Dalarna",
      },
      E1: {
        t: "s",
        v: "Gotland",
        r: "<t>Gotland</t>",
        h: "Gotland",
        w: "Gotland",
      },
      F1: {
        t: "s",
        v: "Gävleborg",
        r: "<t>Gävleborg</t>",
        h: "Gävleborg",
        w: "Gävleborg",
      },
      G1: {
        t: "s",
        v: "Halland",
        r: "<t>Halland</t>",
        h: "Halland",
        w: "Halland",
      },
      H1: {
        t: "s",
        v: "Jämtland_Härjedalen",
        r: "<t>Jämtland_Härjedalen</t>",
        h: "Jämtland_Härjedalen",
        w: "Jämtland_Härjedalen",
      },
      I1: {
        t: "s",
        v: "Jönköping",
        r: "<t>Jönköping</t>",
        h: "Jönköping",
        w: "Jönköping",
      },
      J1: {
        t: "s",
        v: "Kalmar",
        r: "<t>Kalmar</t>",
        h: "Kalmar",
        w: "Kalmar",
      },
      K1: {
        t: "s",
        v: "Kronoberg",
        r: "<t>Kronoberg</t>",
        h: "Kronoberg",
        w: "Kronoberg",
      },
      L1: {
        t: "s",
        v: "Norrbotten",
        r: "<t>Norrbotten</t>",
        h: "Norrbotten",
        w: "Norrbotten",
      },
      M1: { t: "s", v: "Skåne", r: "<t>Skåne</t>", h: "Skåne", w: "Skåne" },
      N1: {
        t: "s",
        v: "Stockholm",
        r: "<t>Stockholm</t>",
        h: "Stockholm",
        w: "Stockholm",
      },
      O1: {
        t: "s",
        v: "Sörmland",
        r: "<t>Sörmland</t>",
        h: "Sörmland",
        w: "Sörmland",
      },
      P1: {
        t: "s",
        v: "Uppsala",
        r: "<t>Uppsala</t>",
        h: "Uppsala",
        w: "Uppsala",
      },
      Q1: {
        t: "s",
        v: "Värmland",
        r: "<t>Värmland</t>",
        h: "Värmland",
        w: "Värmland",
      },
      R1: {
        t: "s",
        v: "Västerbotten",
        r: "<t>Västerbotten</t>",
        h: "Västerbotten",
        w: "Västerbotten",
      },
      S1: {
        t: "s",
        v: "Västernorrland",
        r: "<t>Västernorrland</t>",
        h: "Västernorrland",
        w: "Västernorrland",
      },
      T1: {
        t: "s",
        v: "Västmanland",
        r: "<t>Västmanland</t>",
        h: "Västmanland",
        w: "Västmanland",
      },
      U1: {
        t: "s",
        v: "Västra_Götaland",
        r: "<t>Västra_Götaland</t>",
        h: "Västra_Götaland",
        w: "Västra_Götaland",
      },
      V1: {
        t: "s",
        v: "Örebro",
        r: "<t>Örebro</t>",
        h: "Örebro",
        w: "Örebro",
      },
      W1: {
        t: "s",
        v: "Östergötland",
        r: "<t>Östergötland</t>",
        h: "Östergötland",
        w: "Östergötland",
      },
      A2: { t: "n", v: 43865, w: "2/4/20" },
      B2: { t: "n", v: 1, w: "1" },
      C2: { t: "n", v: 0, w: "0" },
      D2: { t: "n", v: 0, w: "0" },
      E2: { t: "n", v: 0, w: "0" },
      F2: { t: "n", v: 0, w: "0" },
      G2: { t: "n", v: 0, w: "0" },
      H2: { t: "n", v: 0, w: "0" },
      I2: { t: "n", v: 1, w: "1" },
      J2: { t: "n", v: 0, w: "0" },
      K2: { t: "n", v: 0, w: "0" },
      L2: { t: "n", v: 0, w: "0" },
      M2: { t: "n", v: 0, w: "0" },
      N2: { t: "n", v: 0, w: "0" },
      O2: { t: "n", v: 0, w: "0" },
      P2: { t: "n", v: 0, w: "0" },
      Q2: { t: "n", v: 0, w: "0" },
      R2: { t: "n", v: 0, w: "0" },
      S2: { t: "n", v: 0, w: "0" },
      T2: { t: "n", v: 0, w: "0" },
      U2: { t: "n", v: 0, w: "0" },
      V2: { t: "n", v: 0, w: "0" },
      W2: { t: "n", v: 0, w: "0" },
      A3: { t: "n", v: 43866, w: "2/5/20" },
      B3: { t: "n", v: 0, w: "0" },
      C3: { t: "n", v: 0, w: "0" },
      D3: { t: "n", v: 0, w: "0" },
      E3: { t: "n", v: 0, w: "0" },
      F3: { t: "n", v: 0, w: "0" },
      G3: { t: "n", v: 0, w: "0" },
      H3: { t: "n", v: 0, w: "0" },
      I3: { t: "n", v: 0, w: "0" },
      J3: { t: "n", v: 0, w: "0" },
      K3: { t: "n", v: 0, w: "0" },
      L3: { t: "n", v: 0, w: "0" },
      M3: { t: "n", v: 0, w: "0" },
      N3: { t: "n", v: 0, w: "0" },
      O3: { t: "n", v: 0, w: "0" },
      P3: { t: "n", v: 0, w: "0" },
      Q3: { t: "n", v: 0, w: "0" },
      R3: { t: "n", v: 0, w: "0" },
      S3: { t: "n", v: 0, w: "0" },
      T3: { t: "n", v: 0, w: "0" },
      U3: { t: "n", v: 0, w: "0" },
      V3: { t: "n", v: 0, w: "0" },
      W3: { t: "n", v: 0, w: "0" },
      A4: { t: "n", v: 43867, w: "2/6/20" },
      B4: { t: "n", v: 0, w: "0" },
      C4: { t: "n", v: 0, w: "0" },
      D4: { t: "n", v: 0, w: "0" },
      E4: { t: "n", v: 0, w: "0" },
      F4: { t: "n", v: 0, w: "0" },
      G4: { t: "n", v: 0, w: "0" },
      H4: { t: "n", v: 0, w: "0" },
      I4: { t: "n", v: 0, w: "0" },
      J4: { t: "n", v: 0, w: "0" },
      K4: { t: "n", v: 0, w: "0" },
      L4: { t: "n", v: 0, w: "0" },
      M4: { t: "n", v: 0, w: "0" },
      N4: { t: "n", v: 0, w: "0" },
      O4: { t: "n", v: 0, w: "0" },
      P4: { t: "n", v: 0, w: "0" },
      Q4: { t: "n", v: 0, w: "0" },
      R4: { t: "n", v: 0, w: "0" },
      S4: { t: "n", v: 0, w: "0" },
      T4: { t: "n", v: 0, w: "0" },
      U4: { t: "n", v: 0, w: "0" },
      V4: { t: "n", v: 0, w: "0" },
      W4: { t: "n", v: 0, w: "0" },
      A5: { t: "n", v: 43868, w: "2/7/20" },
      B5: { t: "n", v: 0, w: "0" },
      C5: { t: "n", v: 0, w: "0" },
      D5: { t: "n", v: 0, w: "0" },
      E5: { t: "n", v: 0, w: "0" },
      F5: { t: "n", v: 0, w: "0" },
      G5: { t: "n", v: 0, w: "0" },
      H5: { t: "n", v: 0, w: "0" },
      I5: { t: "n", v: 0, w: "0" },
      J5: { t: "n", v: 0, w: "0" },
      K5: { t: "n", v: 0, w: "0" },
      L5: { t: "n", v: 0, w: "0" },
      M5: { t: "n", v: 0, w: "0" },
      N5: { t: "n", v: 0, w: "0" },
      O5: { t: "n", v: 0, w: "0" },
      P5: { t: "n", v: 0, w: "0" },
      Q5: { t: "n", v: 0, w: "0" },
      R5: { t: "n", v: 0, w: "0" },
      S5: { t: "n", v: 0, w: "0" },
      T5: { t: "n", v: 0, w: "0" },
      U5: { t: "n", v: 0, w: "0" },
      V5: { t: "n", v: 0, w: "0" },
      W5: { t: "n", v: 0, w: "0" },
      A6: { t: "n", v: 43869, w: "2/8/20" },
      B6: { t: "n", v: 0, w: "0" },
      C6: { t: "n", v: 0, w: "0" },
      D6: { t: "n", v: 0, w: "0" },
      E6: { t: "n", v: 0, w: "0" },
      F6: { t: "n", v: 0, w: "0" },
      G6: { t: "n", v: 0, w: "0" },
      H6: { t: "n", v: 0, w: "0" },
      I6: { t: "n", v: 0, w: "0" },
      J6: { t: "n", v: 0, w: "0" },
      K6: { t: "n", v: 0, w: "0" },
      L6: { t: "n", v: 0, w: "0" },
      M6: { t: "n", v: 0, w: "0" },
      N6: { t: "n", v: 0, w: "0" },
      O6: { t: "n", v: 0, w: "0" },
      P6: { t: "n", v: 0, w: "0" },
      Q6: { t: "n", v: 0, w: "0" },
      R6: { t: "n", v: 0, w: "0" },
      S6: { t: "n", v: 0, w: "0" },
      T6: { t: "n", v: 0, w: "0" },
      U6: { t: "n", v: 0, w: "0" },
      V6: { t: "n", v: 0, w: "0" },
      W6: { t: "n", v: 0, w: "0" },
      A7: { t: "n", v: 43870, w: "2/9/20" },
      B7: { t: "n", v: 0, w: "0" },
      C7: { t: "n", v: 0, w: "0" },
      D7: { t: "n", v: 0, w: "0" },
      E7: { t: "n", v: 0, w: "0" },
      F7: { t: "n", v: 0, w: "0" },
      G7: { t: "n", v: 0, w: "0" },
      H7: { t: "n", v: 0, w: "0" },
      I7: { t: "n", v: 0, w: "0" },
      J7: { t: "n", v: 0, w: "0" },
      K7: { t: "n", v: 0, w: "0" },
      L7: { t: "n", v: 0, w: "0" },
      M7: { t: "n", v: 0, w: "0" },
      N7: { t: "n", v: 0, w: "0" },
      O7: { t: "n", v: 0, w: "0" },
      P7: { t: "n", v: 0, w: "0" },
      Q7: { t: "n", v: 0, w: "0" },
      R7: { t: "n", v: 0, w: "0" },
      S7: { t: "n", v: 0, w: "0" },
      T7: { t: "n", v: 0, w: "0" },
      U7: { t: "n", v: 0, w: "0" },
      V7: { t: "n", v: 0, w: "0" },
      W7: { t: "n", v: 0, w: "0" },
      A8: { t: "n", v: 43871, w: "2/10/20" },
      B8: { t: "n", v: 0, w: "0" },
      C8: { t: "n", v: 0, w: "0" },
      D8: { t: "n", v: 0, w: "0" },
      E8: { t: "n", v: 0, w: "0" },
      F8: { t: "n", v: 0, w: "0" },
      G8: { t: "n", v: 0, w: "0" },
      H8: { t: "n", v: 0, w: "0" },
      I8: { t: "n", v: 0, w: "0" },
      J8: { t: "n", v: 0, w: "0" },
      K8: { t: "n", v: 0, w: "0" },
      L8: { t: "n", v: 0, w: "0" },
      M8: { t: "n", v: 0, w: "0" },
      N8: { t: "n", v: 0, w: "0" },
      O8: { t: "n", v: 0, w: "0" },
      P8: { t: "n", v: 0, w: "0" },
      Q8: { t: "n", v: 0, w: "0" },
      R8: { t: "n", v: 0, w: "0" },
      S8: { t: "n", v: 0, w: "0" },
      T8: { t: "n", v: 0, w: "0" },
      U8: { t: "n", v: 0, w: "0" },
      V8: { t: "n", v: 0, w: "0" },
      W8: { t: "n", v: 0, w: "0" },
      A9: { t: "n", v: 43872, w: "2/11/20" },
      B9: { t: "n", v: 0, w: "0" },
      C9: { t: "n", v: 0, w: "0" },
      D9: { t: "n", v: 0, w: "0" },
      E9: { t: "n", v: 0, w: "0" },
      F9: { t: "n", v: 0, w: "0" },
      G9: { t: "n", v: 0, w: "0" },
      H9: { t: "n", v: 0, w: "0" },
      I9: { t: "n", v: 0, w: "0" },
      J9: { t: "n", v: 0, w: "0" },
      K9: { t: "n", v: 0, w: "0" },
      L9: { t: "n", v: 0, w: "0" },
      M9: { t: "n", v: 0, w: "0" },
      N9: { t: "n", v: 0, w: "0" },
      O9: { t: "n", v: 0, w: "0" },
      P9: { t: "n", v: 0, w: "0" },
      Q9: { t: "n", v: 0, w: "0" },
      R9: { t: "n", v: 0, w: "0" },
      S9: { t: "n", v: 0, w: "0" },
      T9: { t: "n", v: 0, w: "0" },
      U9: { t: "n", v: 0, w: "0" },
      V9: { t: "n", v: 0, w: "0" },
      W9: { t: "n", v: 0, w: "0" },
      "!margins": {
        left: 0.7,
        right: 0.7,
        top: 0.75,
        bottom: 0.75,
        header: 0.3,
        footer: 0.3,
      },
    },
    "FOHM 11 Feb 2021": {
      "!ref": "A1:A2",
      A1: {
        t: "s",
        v: "Information",
        r: "<t>Information</t>",
        h: "Information",
        w: "Information",
      },
      A2: {
        t: "s",
        v:
          "Data uppdateras vardagar kl 14.00 med data fram till föregående dag. Veckodata uppdateras torsdagar kl 14.00 med föregående veckas data. Läs mer på https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/aktuellt-epidemiologiskt-lage/",
        r:
          "<t>Data uppdateras vardagar kl 14.00 med data fram till föregående dag. Veckodata uppdateras torsdagar kl 14.00 med föregående veckas data. Läs mer på https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/aktuellt-epidemiologiskt-lage/</t>",
        h:
          "Data uppdateras vardagar kl 14.00 med data fram till föregående dag. Veckodata uppdateras torsdagar kl 14.00 med föregående veckas data. Läs mer på https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/aktuellt-epidemiologiskt-lage/",
        w:
          "Data uppdateras vardagar kl 14.00 med data fram till föregående dag. Veckodata uppdateras torsdagar kl 14.00 med föregående veckas data. Läs mer på https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/aktuellt-epidemiologiskt-lage/",
      },
      "!margins": {
        left: 0.7,
        right: 0.7,
        top: 0.75,
        bottom: 0.75,
        header: 0.3,
        footer: 0.3,
      },
    },
  },
}

var parse = require('date-fns/parse')
var isValid = require('date-fns/isValid')
var format = require('date-fns/format')

function iso(date) {
  const parsed = parse(date, "M/d/yy", new Date());
  return isValid(parsed) ? format(parsed, "yyyy-MM-dd") : date;
}

function cases({Sheets}) {
  const sheet = Sheets?.["Antal per dag region"];
  if (!sheet) return {};

  const entries = Object.entries(sheet);

  const columnKeys = Object.fromEntries(
    entries
      .filter(([cell]) => /^[^A]1$/.test(cell))
      .map(([cell, value]) => [/^(\D+)(\d+)$/.exec(cell)[1], value.v])
  );

  const rowKeys = Object.fromEntries(
    entries
      .filter(([cell]) => /^A\d+$/.test(cell))
      .filter(([cell]) => cell !== "A1")
      .map(([cell, value]) => [/^(\D+)(\d+)$/.exec(cell)[2], value.w])
  );

  const columns = Object.fromEntries(
    Object.entries(columnKeys).map(([, value]) => [value, {}])
  );

  entries
    .filter(([cell]) => !/^A/.test(cell))
    .filter(([cell]) => !/\D1$/.test(cell))
    .forEach(([cell, value]) => {
      const match = /^(\D+)(\d+)$/.exec(cell);
      if (match)
        columns[columnKeys[match[1]]][iso(rowKeys[match[2]])] = value.v;
    });
  return columns;
}

module.exports = () => ({
  cases: cases(book),
  population: {
    Totalt_antal_fall: 10230000,
    Blekinge: 159748,
    Dalarna: 287795,
    Gotland: 59636,
    Gävleborg: 287333,
    Halland: 333202,
    Jämtland_Härjedalen: 130697,
    Jönköping: 363351,
    Kalmar: 245415,
    Kronoberg: 201290,
    Norrbotten: 250230,
    Skåne: 1376659,
    Stockholm: 2374550,
    Sörmland: 297169,
    Uppsala: 383044,
    Värmland: 282342,
    Västerbotten: 271621,
    Västernorrland: 245380,
    Västmanland: 275634,
    Västra_Götaland: 1724529,
    Örebro: 304634,
    Östergötland: 465214,
  }
})
